name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codeql-analysis:
    name: Jest Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Jest Test Report
        uses: greguintow/jest-coverage-comment@0.1.11
